### ISSUE TITLE
How to login? 

### ISSUE THREAD

**Issue by EvgenyLeukhin** [konsumer/gatsby-starter-bootstrap-netlify#7]
On this admin page: http://localhost:8000/admin/index.html#/

**Comment by konsumer** [comment]
Once you have deployed to netlify, you can go to https://yoursite/admin

**Comment by EvgenyLeukhin** [comment]
How to get this URL-address to enter the administration mode? Need to create an account on the Netlify site?
![screenshot_1](https://user-images.githubusercontent.com/18072088/41188285-eba313ee-6bdc-11e8-828f-6046259caadf.jpg)

**Comment by EvgenyLeukhin** [comment]
I understood. Thanks a lot!
