### ISSUE TITLE
netlify identity is not working

### ISSUE THREAD

**Issue by AjGabriel** [konsumer/gatsby-starter-bootstrap-netlify#8]
I have tried to clone this repo and add the site to netlify. The website is up and running but when I go to the _my_site_/admin and sign up, I get this weird error.
![screen shot 2018-08-10 at 1 34 20 pm](https://user-images.githubusercontent.com/10936392/43939991-fd6c943a-9c9f-11e8-88f4-6459108e576c.png)

**Comment by FMGordillo** [comment]
Mine says `Unexpected end of JSON input` and before another different error. Vary...

**Comment by FMGordillo** [comment]
Seeing the `resources` tab in my browser, i've seen this request ( [**`https://mystifying-booth-d2d620.netlify.com/.netlify/git/settings`**](https://mystifying-booth-d2d620.netlify.com/.netlify/git/settings) ), i went there but I can't see anything.

**Comment by konsumer** [comment]
I think this should be resolved. closing for now, but feel free to comment more, if not.
